"""Real general@incubator.apache.org messages, captured for offline tests.

Bodies are verbatim from the Apache Cloudberry (Incubating) 2.1.0-rc1 and
2.1.0-rc2 release vote threads, quoted text and all. Pony Mail returns no
thread id for these (``tid`` is None), which is why replies have to be
grouped by subject. Nothing here touches the network.
"""

from __future__ import annotations

from typing import Any

RC1_VOTE_ID = "pxcqfrbl8bdp256yxtxx5zr60y79nrkn"
RC1_JB_MINUS_ONE_ID = "xfcf4rxpmj071no5jcx9693mh1mmyml9"
RC1_JUSTIN_REPLY_ID = "hrj8wfcyjllygq93qjzgbzmcyfg9h4f4"
RC2_VOTE_ID = "ojromk12r5y8802jp3qy16w9hq0fxk1o"
RC2_SHUXIN_PLUS_ONE_ID = "tkdhqs8bk706fccjzpn5h2hdz2vy3fy5"
RC2_RESULT_ID = "j9yoh66yx9j1ccdgqpys7blhoyqzshh7"

CLOUDBERRY_EMAILS: dict[str, Any] = {
    "pxcqfrbl8bdp256yxtxx5zr60y79nrkn": {
        "mid": "pxcqfrbl8bdp256yxtxx5zr60y79nrkn",
        "tid": None,
        "epoch": 1773293940,
        "date": "2026/03/12 05:39:00",
        "subject": "[VOTE] Release Apache Cloudberry (Incubating) 2.1.0-rc1",
        "message-id": "<CACz0+mOZtQY0MH-1Kkt4y966YP8nqMmyyRfhC1kDLqAxpoTeyg@mail.gmail.com>",
        "private": False,
        "from": "Dianjin Wang <wa...@gmail.com>",
        "body": "Hello Incubator Community,\n"
        "\n"
        "This is a call for a vote to release Apache "
        "Cloudberry (Incubating) 2.1.0-rc1.\n"
        "\n"
        "The Apache Cloudberry (Incubating) community has "
        "voted to release\n"
        "version 2.1.0-rc1. We now kindly request the "
        "Incubator PMC's approval.\n"
        "\n"
        "Community vote thread:\n"
        "https://lists.apache.org/thread/f1wyc9sjxg5rt4comdgfsfp2vtpm5mqf\n"
        "\n"
        "Vote result thread:\n"
        "https://lists.apache.org/thread/yds1mkcn3v0c4xmdzh897xwnpdobgcnf\n"
        "\n"
        "Release candidate artifacts:\n"
        "https://dist.apache.org/repos/dist/dev/incubator/cloudberry/2.1.0-incubating-rc1/\n"
        "\n"
        "Git tag & commit for the release:\n"
        "- "
        "https://github.com/apache/cloudberry/tree/2.1.0-incubating-rc1 "
        "(bdf90c5)\n"
        "- "
        "https://github.com/apache/cloudberry-backup/tree/2.1.0-incubating-rc1\n"
        "( c909fbe )\n"
        "- "
        "https://github.com/apache/cloudberry-pxf/tree/2.1.0-incubating-rc1 "
        "(59dcedd)\n"
        "\n"
        "The artifacts have been signed with key\n"
        "[9A36AA272348A207E193A49C500708B75754FB7C], "
        "corresponding to\n"
        "djwang@apache.org, available here:\n"
        "https://downloads.apache.org/incubator/cloudberry/KEYS\n"
        "\n"
        "Please vote on releasing this candidate as Apache "
        "Cloudberry (Incubating) 2.1.0.\n"
        "\n"
        "[ ] +1 Approve the release\n"
        "[ ] 0 No opinion\n"
        "[ ] -1 Disapprove (please explain why)\n"
        "\n"
        "This vote will be open for at least 72 hours.\n"
        "\n"
        "Checklist for reference:\n"
        "\n"
        "[ ] Download links are valid and accessible.\n"
        "[ ] GPG signature is valid for the release artifact "
        "using the KEYS file.\n"
        "[ ] SHA512 checksums are correct and verified.\n"
        "[ ] Source release artifact filename includes "
        '"incubating".\n'
        "[ ] LICENSE, NOTICE, and DISCLAIMER files exist and "
        "are accurate.\n"
        "[ ] No unexpected binary files in the source "
        "release.\n"
        "[ ] All source files have appropriate ASF headers "
        "(excluding generated\n"
        "files and legacy files).\n"
        "[ ] Build completes successfully from source with "
        "clear instructions.\n"
        "\n"
        "More detailed checklist, please refer to:\n"
        "https://github.com/apache/cloudberry/wiki/Source-Release-Checklist\n"
        "\n"
        "Build/Install guides (for reference):\n"
        "- cloudberry: "
        "https://cloudberry.apache.org/docs/deployment/quick-build#for-apache-cloudberry-210\n"
        "- cloudberry-pxf:\n"
        "https://github.com/apache/cloudberry-pxf/blob/2.1.0-incubating-rc1/README.md\n"
        "- cloudberry-backup:\n"
        "https://github.com/apache/cloudberry-backup/blob/2.1.0-incubating-rc1/README.md\n"
        "\n"
        "To learn more about Apache Cloudberry (Incubating), "
        "please see\n"
        "https://cloudberry.apache.org/\n"
        "\n"
        "\n"
        "Best,\n"
        "Dianjin Wang\n"
        "On behalf of the Apache Cloudberry (Incubating) "
        "community\n"
        "\n"
        "---------------------------------------------------------------------\n"
        "To unsubscribe, e-mail: "
        "general-unsubscribe@incubator.apache.org\n"
        "For additional commands, e-mail: "
        "general-help@incubator.apache.org\n"
        "\n",
        "in-reply-to": "",
        "list": "general@incubator.apache.org",
    },
    "xfcf4rxpmj071no5jcx9693mh1mmyml9": {
        "mid": "xfcf4rxpmj071no5jcx9693mh1mmyml9",
        "tid": None,
        "epoch": 1773384550,
        "date": "2026/03/13 06:49:10",
        "subject": "Re: [VOTE] Release Apache Cloudberry (Incubating) 2.1.0-rc1",
        "message-id": "<CAB8EV3RpJWVGfnQEGXxTYdVrWJtBOrtktQMp6xcqhf8nX6U7Mg@mail.gmail.com>",
        "private": False,
        "from": "Jean-Baptiste Onofré <jb...@nanthrax.net>",
        "body": "-1 (binding), because cloudberry source files don't "
        "have ASF header (in\n"
        "backup and pxf), cloudberry-pxf source includes "
        "gradle-wrapper.jar file.\n"
        "\n"
        "I checked:\n"
        "- cloudberry src\n"
        "-- incubating is in the name/version\n"
        "-- signature and checksum are good\n"
        "-- DISCLAIMER is present\n"
        "-- LICENSE and NOTICE are good. nit: in the LICENSE "
        "file there is a\n"
        "typo: licenses/licenses/LICENSE-isc.txt instead of "
        "licenses/LICENSE-isc.txt\n"
        "(double licenses)\n"
        "-- No binary/compiled file found (NB: "
        "src/bin/pgevent/MSG00001.bin is there\n"
        "but it's not a binary file)\n"
        "-- ASF header is present in all expected files "
        "(nit: SQL files could\n"
        "contain the ASF header)\n"
        "- cloudberry backup\n"
        "-- incubating is in the name/version\n"
        "-- signature and checksum are good\n"
        "-- DISCLAIMER is present\n"
        "-- LICENSE and NOTICE are good\n"
        "-- No binary/compiled file found. NB: can you "
        "clarify if the tar.gz files\n"
        "located in end_to_end/resources are required ?\n"
        "-- ASF header is missing in go files, in SQL files, "
        "sh script, yaml files\n"
        "- cloudberry pxf\n"
        "-- incubating is in the name/version\n"
        "-- signature and checksum are good\n"
        "-- DISCLAIMER is present\n"
        "-- LICENSE and NOTICE are good.\n"
        "-- No compiled files. NB: the source distribution "
        "includes a few gz files\n"
        "(tweets.tar.gz, ...). Also gradle-wrapper.jar "
        "should not be part of the\n"
        "source distribution\n"
        "-- ASF header is missing in java files, xml files, "
        "sh scripts, ...\n"
        "\n"
        "Regards\n"
        "JB\n"
        "\n"
        "On Thu, Mar 12, 2026 at 6:42\u202fAM Dianjin Wang "
        "<wa...@gmail.com> wrote:\n"
        "\n"
        "> Hello Incubator Community,\n"
        ">\n"
        "> This is a call for a vote to release Apache "
        "Cloudberry (Incubating)\n"
        "> 2.1.0-rc1.\n"
        ">\n"
        "> The Apache Cloudberry (Incubating) community has "
        "voted to release\n"
        "> version 2.1.0-rc1. We now kindly request the "
        "Incubator PMC's approval.\n"
        ">\n"
        "> Community vote thread:\n"
        "> "
        "https://lists.apache.org/thread/f1wyc9sjxg5rt4comdgfsfp2vtpm5mqf\n"
        ">\n"
        "> Vote result thread:\n"
        "> "
        "https://lists.apache.org/thread/yds1mkcn3v0c4xmdzh897xwnpdobgcnf\n"
        ">\n"
        "> Release candidate artifacts:\n"
        ">\n"
        "> "
        "https://dist.apache.org/repos/dist/dev/incubator/cloudberry/2.1.0-incubating-rc1/\n"
        ">\n"
        "> Git tag & commit for the release:\n"
        "> - "
        "https://github.com/apache/cloudberry/tree/2.1.0-incubating-rc1 "
        "(bdf90c5)\n"
        "> - "
        "https://github.com/apache/cloudberry-backup/tree/2.1.0-incubating-rc1\n"
        "> ( c909fbe )\n"
        "> - "
        "https://github.com/apache/cloudberry-pxf/tree/2.1.0-incubating-rc1\n"
        "> (59dcedd)\n"
        ">\n"
        "> The artifacts have been signed with key\n"
        "> [9A36AA272348A207E193A49C500708B75754FB7C], "
        "corresponding to\n"
        "> djwang@apache.org, available here:\n"
        "> "
        "https://downloads.apache.org/incubator/cloudberry/KEYS\n"
        ">\n"
        "> Please vote on releasing this candidate as Apache "
        "Cloudberry (Incubating)\n"
        "> 2.1.0.\n"
        ">\n"
        "> [ ] +1 Approve the release\n"
        "> [ ] 0 No opinion\n"
        "> [ ] -1 Disapprove (please explain why)\n"
        ">\n"
        "> This vote will be open for at least 72 hours.\n"
        ">\n"
        "> Checklist for reference:\n"
        ">\n"
        "> [ ] Download links are valid and accessible.\n"
        "> [ ] GPG signature is valid for the release "
        "artifact using the KEYS file.\n"
        "> [ ] SHA512 checksums are correct and verified.\n"
        "> [ ] Source release artifact filename includes "
        '"incubating".\n'
        "> [ ] LICENSE, NOTICE, and DISCLAIMER files exist "
        "and are accurate.\n"
        "> [ ] No unexpected binary files in the source "
        "release.\n"
        "> [ ] All source files have appropriate ASF headers "
        "(excluding generated\n"
        "> files and legacy files).\n"
        "> [ ] Build completes successfully from source with "
        "clear instructions.\n"
        ">\n"
        "> More detailed checklist, please refer to:\n"
        "> "
        "https://github.com/apache/cloudberry/wiki/Source-Release-Checklist\n"
        ">\n"
        "> Build/Install guides (for reference):\n"
        "> - cloudberry:\n"
        "> "
        "https://cloudberry.apache.org/docs/deployment/quick-build#for-apache-cloudberry-210\n"
        "> - cloudberry-pxf:\n"
        ">\n"
        "> "
        "https://github.com/apache/cloudberry-pxf/blob/2.1.0-incubating-rc1/README.md\n"
        "> - cloudberry-backup:\n"
        ">\n"
        "> "
        "https://github.com/apache/cloudberry-backup/blob/2.1.0-incubating-rc1/README.md\n"
        ">\n"
        "> To learn more about Apache Cloudberry "
        "(Incubating), please see\n"
        "> https://cloudberry.apache.org/\n"
        ">\n"
        ">\n"
        "> Best,\n"
        "> Dianjin Wang\n"
        "> On behalf of the Apache Cloudberry (Incubating) "
        "community\n"
        ">\n"
        "> "
        "---------------------------------------------------------------------\n"
        "> To unsubscribe, e-mail: "
        "general-unsubscribe@incubator.apache.org\n"
        "> For additional commands, e-mail: "
        "general-help@incubator.apache.org\n"
        ">\n"
        ">\n",
        "in-reply-to": "<CACz0+mOZtQY0MH-1Kkt4y966YP8nqMmyyRfhC1kDLqAxpoTeyg@mail.gmail.com>",
        "list": "general@incubator.apache.org",
    },
    "dzzl7thfszl78m7cgxpc9h91pk5s0rmd": {
        "mid": "dzzl7thfszl78m7cgxpc9h91pk5s0rmd",
        "tid": None,
        "epoch": 1773388262,
        "date": "2026/03/13 07:51:02",
        "subject": "Re: [VOTE] Release Apache Cloudberry (Incubating) 2.1.0-rc1",
        "message-id": "<CAB8EV3T_AAMTLmMhDhcprutJ2MQgVMHzAzkzrYqELGnhin76fw@mail.gmail.com>",
        "private": False,
        "from": "Jean-Baptiste Onofré <jb...@nanthrax.net>",
        "body": "Just to be clarify:\n"
        "1. the files missing ASF in cloudberry-pxf (java, "
        "c, etc) are not blocker\n"
        "because they are coming from Greenplum\n"
        "2. in cloudberry-backup, it's not clear to me where "
        "the go files are coming\n"
        "from (the LICENSE mentions Greenplum, but doesn't "
        "list the go files). It\n"
        "seems that the go files need the ASF header.\n"
        "\n"
        "Regards\n"
        "JB\n"
        "\n"
        "On Thu, Mar 12, 2026 at 6:42\u202fAM Dianjin Wang "
        "<wa...@gmail.com> wrote:\n"
        "\n"
        "> Hello Incubator Community,\n"
        ">\n"
        "> This is a call for a vote to release Apache "
        "Cloudberry (Incubating)\n"
        "> 2.1.0-rc1.\n"
        ">\n"
        "> The Apache Cloudberry (Incubating) community has "
        "voted to release\n"
        "> version 2.1.0-rc1. We now kindly request the "
        "Incubator PMC's approval.\n"
        ">\n"
        "> Community vote thread:\n"
        "> "
        "https://lists.apache.org/thread/f1wyc9sjxg5rt4comdgfsfp2vtpm5mqf\n"
        ">\n"
        "> Vote result thread:\n"
        "> "
        "https://lists.apache.org/thread/yds1mkcn3v0c4xmdzh897xwnpdobgcnf\n"
        ">\n"
        "> Release candidate artifacts:\n"
        ">\n"
        "> "
        "https://dist.apache.org/repos/dist/dev/incubator/cloudberry/2.1.0-incubating-rc1/\n"
        ">\n"
        "> Git tag & commit for the release:\n"
        "> - "
        "https://github.com/apache/cloudberry/tree/2.1.0-incubating-rc1 "
        "(bdf90c5)\n"
        "> - "
        "https://github.com/apache/cloudberry-backup/tree/2.1.0-incubating-rc1\n"
        "> ( c909fbe )\n"
        "> - "
        "https://github.com/apache/cloudberry-pxf/tree/2.1.0-incubating-rc1\n"
        "> (59dcedd)\n"
        ">\n"
        "> The artifacts have been signed with key\n"
        "> [9A36AA272348A207E193A49C500708B75754FB7C], "
        "corresponding to\n"
        "> djwang@apache.org, available here:\n"
        "> "
        "https://downloads.apache.org/incubator/cloudberry/KEYS\n"
        ">\n"
        "> Please vote on releasing this candidate as Apache "
        "Cloudberry (Incubating)\n"
        "> 2.1.0.\n"
        ">\n"
        "> [ ] +1 Approve the release\n"
        "> [ ] 0 No opinion\n"
        "> [ ] -1 Disapprove (please explain why)\n"
        ">\n"
        "> This vote will be open for at least 72 hours.\n"
        ">\n"
        "> Checklist for reference:\n"
        ">\n"
        "> [ ] Download links are valid and accessible.\n"
        "> [ ] GPG signature is valid for the release "
        "artifact using the KEYS file.\n"
        "> [ ] SHA512 checksums are correct and verified.\n"
        "> [ ] Source release artifact filename includes "
        '"incubating".\n'
        "> [ ] LICENSE, NOTICE, and DISCLAIMER files exist "
        "and are accurate.\n"
        "> [ ] No unexpected binary files in the source "
        "release.\n"
        "> [ ] All source files have appropriate ASF headers "
        "(excluding generated\n"
        "> files and legacy files).\n"
        "> [ ] Build completes successfully from source with "
        "clear instructions.\n"
        ">\n"
        "> More detailed checklist, please refer to:\n"
        "> "
        "https://github.com/apache/cloudberry/wiki/Source-Release-Checklist\n"
        ">\n"
        "> Build/Install guides (for reference):\n"
        "> - cloudberry:\n"
        "> "
        "https://cloudberry.apache.org/docs/deployment/quick-build#for-apache-cloudberry-210\n"
        "> - cloudberry-pxf:\n"
        ">\n"
        "> "
        "https://github.com/apache/cloudberry-pxf/blob/2.1.0-incubating-rc1/README.md\n"
        "> - cloudberry-backup:\n"
        ">\n"
        "> "
        "https://github.com/apache/cloudberry-backup/blob/2.1.0-incubating-rc1/README.md\n"
        ">\n"
        "> To learn more about Apache Cloudberry "
        "(Incubating), please see\n"
        "> https://cloudberry.apache.org/\n"
        ">\n"
        ">\n"
        "> Best,\n"
        "> Dianjin Wang\n"
        "> On behalf of the Apache Cloudberry (Incubating) "
        "community\n"
        ">\n"
        "> "
        "---------------------------------------------------------------------\n"
        "> To unsubscribe, e-mail: "
        "general-unsubscribe@incubator.apache.org\n"
        "> For additional commands, e-mail: "
        "general-help@incubator.apache.org\n"
        ">\n"
        ">\n",
        "in-reply-to": "<CACz0+mOZtQY0MH-1Kkt4y966YP8nqMmyyRfhC1kDLqAxpoTeyg@mail.gmail.com>",
        "list": "general@incubator.apache.org",
    },
    "l72ymslr2mtk4bjj0gjsysf47ph8nnsn": {
        "mid": "l72ymslr2mtk4bjj0gjsysf47ph8nnsn",
        "tid": None,
        "epoch": 1773401117,
        "date": "2026/03/13 11:25:17",
        "subject": "Re: [VOTE] Release Apache Cloudberry (Incubating) 2.1.0-rc1",
        "message-id": "<pony-907a914e-dee6-41e9-a74a-03f991b02b60-general@incubator.apache.org>",
        "private": False,
        "from": "Dianjin Wang <dj...@apache.org>",
        "body": "Hi JB,\n"
        "\n"
        "Thank you very much for your detailed review and "
        "the thorough check of our 2.1.0-rc1.\n"
        "\n"
        "> -- LICENSE and NOTICE are good. nit: in the "
        "LICENSE file there is a\n"
        "> typo: licenses/licenses/LICENSE-isc.txt instead "
        "of licenses/LICENSE-isc.txt\n"
        "> (double licenses)\n"
        "\n"
        "Good catch! We appreciate you spotting this. This "
        "is indeed a typo in the doc.\n"
        "\n"
        "> - cloudberry backup\n"
        "> -- No binary/compiled file found. NB: can you "
        "clarify if the tar.gz files\n"
        "> located in end_to_end/resources are required ?\n"
        "\n"
        "These files are required for our end-to-end "
        "integration tests. They are compressed formats of "
        "plain text data used as test resources. We prefer "
        "to keep them for test but will add explicit "
        "clarifications in a `README.apache.md` or similar "
        "documentation in future versions.\n"
        "\n"
        "> - cloudberry pxf\n"
        "> -- No compiled files. NB: the source distribution "
        "includes a few gz files\n"
        "> (tweets.tar.gz, ...). Also gradle-wrapper.jar "
        "should not be part of the\n"
        "> source distribution\n"
        "\n"
        "Similar to the above, these .gz files are also test "
        "files in compressed plain text format. For "
        "gradle-warpper.jar, we will see how to deal with it "
        "for better compliance without affecting the program "
        "building & running.\n"
        "\n"
        "> Just to be clarify:\n"
        "> 2. in cloudberry-backup, it's not clear to me "
        "where the go files are coming\n"
        "> from (the LICENSE mentions Greenplum, but doesn't "
        "list the go files). It\n"
        "> seems that the go files need the ASF header.\n"
        "\n"
        "You are correct. These Go files originated from the "
        "Greenplum project. Sorry for not explicitly listing "
        "them in a more detailed list in the `LICENSE`.\n"
        "\n"
        "BTW, would you recommend we cancel this RC and "
        "prepare RC2 to address these issues specifically, "
        "or would it be acceptable to include these fixes in "
        "the next release? We are prepared to roll out RC2 "
        "if you believe these points are blockers for the "
        "current vote.\n"
        "\n"
        "Thank you again for your guidance!\n"
        "\n"
        "Best,\n"
        "Dianjin Wang\n"
        "\n"
        "---------------------------------------------------------------------\n"
        "To unsubscribe, e-mail: "
        "general-unsubscribe@incubator.apache.org\n"
        "For additional commands, e-mail: "
        "general-help@incubator.apache.org\n"
        "\n",
        "in-reply-to": "<CAB8EV3RpJWVGfnQEGXxTYdVrWJtBOrtktQMp6xcqhf8nX6U7Mg@mail.gmail.com>",
        "list": "general@incubator.apache.org",
    },
    "zd2jtq0cso6rotj1hosnx155cttypb1d": {
        "mid": "zd2jtq0cso6rotj1hosnx155cttypb1d",
        "tid": None,
        "epoch": 1773403152,
        "date": "2026/03/13 11:59:12",
        "subject": "Re: [VOTE] Release Apache Cloudberry (Incubating) 2.1.0-rc1",
        "message-id": "<CAB8EV3QJT91_2QhZwW_6tdszoankqBpo_DFKUZz4Z45sNBd9_Q@mail.gmail.com>",
        "private": False,
        "from": "Jean-Baptiste Onofré <jb...@nanthrax.net>",
        "body": "Hi\n"
        "\n"
        "Thanks for the update !\n"
        "\n"
        "As the LICENSE is not fully correct for "
        "cloudberry-backup (listing go\n"
        "files), if it's not painful, I would suggest "
        "preparing a RC2 fixing the\n"
        "issue.\n"
        "\n"
        "Thanks again, much appreciated!\n"
        "\n"
        "Regards\n"
        "JB\n"
        "\n"
        "On Fri, Mar 13, 2026 at 12:25\u202fPM Dianjin Wang "
        "<dj...@apache.org> wrote:\n"
        "\n"
        "> Hi JB,\n"
        ">\n"
        "> Thank you very much for your detailed review and "
        "the thorough check of our\n"
        "> 2.1.0-rc1.\n"
        ">\n"
        "> > -- LICENSE and NOTICE are good. nit: in the "
        "LICENSE file there is a\n"
        "> > typo: licenses/licenses/LICENSE-isc.txt instead "
        "of\n"
        "> licenses/LICENSE-isc.txt\n"
        "> > (double licenses)\n"
        ">\n"
        "> Good catch! We appreciate you spotting this. This "
        "is indeed a typo in the\n"
        "> doc.\n"
        ">\n"
        "> > - cloudberry backup\n"
        "> > -- No binary/compiled file found. NB: can you "
        "clarify if the tar.gz files\n"
        "> > located in end_to_end/resources are required ?\n"
        ">\n"
        "> These files are required for our end-to-end "
        "integration tests. They are\n"
        "> compressed formats of plain text data used as "
        "test resources. We prefer to\n"
        "> keep them for test but will add explicit "
        "clarifications in a `\n"
        "> README.apache.md` or similar documentation in "
        "future versions.\n"
        ">\n"
        "> > - cloudberry pxf\n"
        "> > -- No compiled files. NB: the source "
        "distribution includes a few gz files\n"
        "> > (tweets.tar.gz, ...). Also gradle-wrapper.jar "
        "should not be part of the\n"
        "> > source distribution\n"
        ">\n"
        "> Similar to the above, these .gz files are also "
        "test files in compressed\n"
        "> plain text format. For gradle-warpper.jar, we "
        "will see how to deal with it\n"
        "> for better compliance without affecting the "
        "program building & running.\n"
        ">\n"
        "> > Just to be clarify:\n"
        "> > 2. in cloudberry-backup, it's not clear to me "
        "where the go files are\n"
        "> coming\n"
        "> > from (the LICENSE mentions Greenplum, but "
        "doesn't list the go files). It\n"
        "> > seems that the go files need the ASF header.\n"
        ">\n"
        "> You are correct. These Go files originated from "
        "the Greenplum project.\n"
        "> Sorry for not explicitly listing them in a more "
        "detailed list in the\n"
        "> `LICENSE`.\n"
        ">\n"
        "> BTW, would you recommend we cancel this RC and "
        "prepare RC2 to address\n"
        "> these issues specifically, or would it be "
        "acceptable to include these fixes\n"
        "> in the next release? We are prepared to roll out "
        "RC2 if you believe these\n"
        "> points are blockers for the current vote.\n"
        ">\n"
        "> Thank you again for your guidance!\n"
        ">\n"
        "> Best,\n"
        "> Dianjin Wang\n"
        ">\n"
        "> "
        "---------------------------------------------------------------------\n"
        "> To unsubscribe, e-mail: "
        "general-unsubscribe@incubator.apache.org\n"
        "> For additional commands, e-mail: "
        "general-help@incubator.apache.org\n"
        ">\n"
        ">\n",
        "in-reply-to": "<pony-907a914e-dee6-41e9-a74a-03f991b02b60-general@incubator.apache.org>",
        "list": "general@incubator.apache.org",
    },
    "hrj8wfcyjllygq93qjzgbzmcyfg9h4f4": {
        "mid": "hrj8wfcyjllygq93qjzgbzmcyfg9h4f4",
        "tid": None,
        "epoch": 1773455030,
        "date": "2026/03/14 02:23:50",
        "subject": "Re: [VOTE] Release Apache Cloudberry (Incubating) 2.1.0-rc1",
        "message-id": "<3C645584-B05F-44BB-85F6-6E8F9B1E8171@classsoftware.com>",
        "private": False,
        "from": "Justin Mclean <ju...@classsoftware.com>",
        "body": "Hi,\n"
        "\n"
        ">> - cloudberry backup\n"
        ">> -- No binary/compiled file found. NB: can you "
        "clarify if the tar.gz files\n"
        ">> located in end_to_end/resources are required ?\n"
        "> \n"
        "> These files are required for our end-to-end "
        "integration tests. They are compressed formats of "
        "plain text data used as test resources. We prefer "
        "to keep them for test but will add explicit "
        "clarifications in a `README.apache.md` or similar "
        "documentation in future versions.\n"
        "\n"
        "Compressed files are fine if they do not contain "
        "compiled code.\n"
        "\n"
        ">> - cloudberry pxf\n"
        ">> -- No compiled files. NB: the source "
        "distribution includes a few gz files\n"
        ">> (tweets.tar.gz, ...). Also gradle-wrapper.jar "
        "should not be part of the\n"
        ">> source distribution\n"
        "> \n"
        "> Similar to the above, these .gz files are also "
        "test files in compressed plain text format. For "
        "gradle-warpper.jar, we will see how to deal with it "
        "for better compliance without affecting the program "
        "building & running.\n"
        "\n"
        "gradle-wrapper.jar cannot be included in a source "
        "release as it contains compiled code.\n"
        "\n"
        "Kind Regards,\n"
        "Justin\n"
        "---------------------------------------------------------------------\n"
        "To unsubscribe, e-mail: "
        "general-unsubscribe@incubator.apache.org\n"
        "For additional commands, e-mail: "
        "general-help@incubator.apache.org\n"
        "\n",
        "in-reply-to": "<pony-907a914e-dee6-41e9-a74a-03f991b02b60-general@incubator.apache.org>",
        "list": "general@incubator.apache.org",
    },
    "xdg2b89wkhrljql5lm2j0wlzccld505o": {
        "mid": "xdg2b89wkhrljql5lm2j0wlzccld505o",
        "tid": None,
        "epoch": 1773628257,
        "date": "2026/03/16 02:30:57",
        "subject": "Re: [VOTE] Release Apache Cloudberry (Incubating) 2.1.0-rc1",
        "message-id": "<pony-ac969478-8e1a-43a6-aa48-ae576683fa5f-general@incubator.apache.org>",
        "private": False,
        "from": "Dianjin Wang <dj...@apache.org>",
        "body": "Hi, Justin, \n"
        "\n"
        "> Compressed files are fine if they do not contain "
        "compiled code.\n"
        "\n"
        "Appreciate your feedback on these. We will review "
        "these files and, for the next RC, we will provide "
        "clearer documentation in README.apache.md.\n"
        "\n"
        "> gradle-wrapper.jar cannot be included in a source "
        "release as it contains compiled code.\n"
        "\n"
        "On gradle-wrapper.jar in cloudberry-pxf: Thank you "
        "for the clarification. We will remove the .jar file "
        "from the source package in the next RC and update "
        "our build instructions to ensure users can still "
        "build the project.\n"
        "\n"
        "Therefore, I am withdrawing the vote for Apache "
        "Cloudberry (Incubating) 2.1.0-rc1. We will address "
        "the identified issues and will prepare RC2 for a "
        "new round of voting shortly.\n"
        "\n"
        "Thank you all again for your thorough review and "
        "suggestions!\n"
        "\n"
        "Best,\n"
        "Dianjin Wang\n"
        "\n"
        "---------------------------------------------------------------------\n"
        "To unsubscribe, e-mail: "
        "general-unsubscribe@incubator.apache.org\n"
        "For additional commands, e-mail: "
        "general-help@incubator.apache.org\n"
        "\n",
        "in-reply-to": "<3C645584-B05F-44BB-85F6-6E8F9B1E8171@classsoftware.com>",
        "list": "general@incubator.apache.org",
    },
    "ojromk12r5y8802jp3qy16w9hq0fxk1o": {
        "mid": "ojromk12r5y8802jp3qy16w9hq0fxk1o",
        "tid": None,
        "epoch": 1774499940,
        "date": "2026/03/26 04:39:00",
        "subject": "[VOTE] Release Apache Cloudberry (Incubating) 2.1.0-rc2",
        "message-id": "<CACz0+mP279OmaTXiD44aMiw2u86e5JYaWg0j7d3SHWKPcaCgiQ@mail.gmail.com>",
        "private": False,
        "from": "Dianjin Wang <wa...@gmail.com>",
        "body": "Hello Incubator Community,\n"
        "\n"
        "This is a call for a vote to release Apache "
        "Cloudberry (Incubating) 2.1.0-rc2.\n"
        "\n"
        "The Apache Cloudberry (Incubating) community has "
        "voted to release\n"
        "version 2.1.0-rc2. We now kindly request the "
        "Incubator PMC's approval.\n"
        "\n"
        "\n"
        "**Key changes since 2.1.0-rc1**\n"
        "\n"
        "The main changes are to fix the license issues "
        "pointed out in the RC1,\n"
        "including:\n"
        "\n"
        "- cloudberry:\n"
        "* No changes. Fixes for the license typo and "
        "documentation updates\n"
        "pointed out during the RC1 round will be included "
        "in the next release.\n"
        "\n"
        "- cloudberry-pxf\n"
        "* Add `cloudberry-pxf-release.sh` to assist the "
        "release manager in\n"
        "creating ASF releases.\n"
        "* Update `Makefile` to include `fdw` in DEB/RPM "
        "packages.\n"
        "* Remove `gradle-wrapper.jar` from the source tree; "
        "it is now\n"
        "downloaded and validated during the build process.\n"
        "* Add ASF license headers to files created by the "
        "Cloudberry community.\n"
        "* Update the `LICENSE` file to reflect the latest "
        "changes from third-parties.\n"
        "* Add a new `README.apache.md` to document "
        "historical attributions\n"
        "and describe test archive files.\n"
        "* Add a new `pom.xml` with necessary exclusions for "
        "running `mvn\n"
        "apache-rat:check` during license audits.\n"
        "* Add `.github/workflows/apache-rat-audit.yml` to "
        "perform regular\n"
        "license checks on PRs and pushes.\n"
        "\n"
        "- cloudberry-backup\n"
        "* Update the `LICENSE` file with correct "
        "open-source attributions.\n"
        "* Add a new `README.apache.md` to document "
        "historical attributions\n"
        "and describe test archive files.\n"
        "* Add a new `pom.xml` with necessary exclusions for "
        "running `mvn\n"
        "apache-rat:check` during license audits.\n"
        "* Add `.github/workflows/apache-rat-audit.yml` to "
        "perform regular\n"
        "license checks on PRs and pushes.\n"
        "\n"
        "\n"
        "Community vote thread:\n"
        "https://lists.apache.org/thread/7ozvb3808jxyyr105kbphhpj1dz5g7yk\n"
        "\n"
        "Vote result thread:\n"
        "https://lists.apache.org/thread/xzqzp6scvxd00gfxx685nks7ykc7bpcr\n"
        "\n"
        "Release candidate artifacts:\n"
        "https://dist.apache.org/repos/dist/dev/incubator/cloudberry/2.1.0-incubating-rc2/\n"
        "\n"
        "Git tag & commit for the release:\n"
        "- "
        "https://github.com/apache/cloudberry/tree/2.1.0-incubating-rc2 "
        "(bdf90c5)\n"
        "- "
        "https://github.com/apache/cloudberry-backup/tree/2.1.0-incubating-rc2\n"
        "( 3b5451f )\n"
        "- "
        "https://github.com/apache/cloudberry-pxf/tree/2.1.0-incubating-rc2 "
        "(118f588)\n"
        "\n"
        "The artifacts have been signed with key\n"
        "[9A36AA272348A207E193A49C500708B75754FB7C], "
        "corresponding to\n"
        "djwang@apache.org, available here:\n"
        "https://downloads.apache.org/incubator/cloudberry/KEYS\n"
        "\n"
        "Please vote on releasing this candidate as Apache "
        "Cloudberry (Incubating) 2.1.0.\n"
        "\n"
        "[ ] +1 Approve the release\n"
        "[ ] 0 No opinion\n"
        "[ ] -1 Disapprove (please explain why)\n"
        "\n"
        "This vote will be open for at least 72 hours.\n"
        "\n"
        "Checklist for reference:\n"
        "\n"
        "[ ] Download links are valid and accessible.\n"
        "[ ] GPG signature is valid for the release artifact "
        "using the KEYS file.\n"
        "[ ] SHA512 checksums are correct and verified.\n"
        "[ ] Source release artifact filename includes "
        '"incubating".\n'
        "[ ] LICENSE, NOTICE, and DISCLAIMER files exist and "
        "are accurate.\n"
        "[ ] No unexpected binary files in the source "
        "release.\n"
        "[ ] All source files have appropriate ASF headers "
        "(excluding generated\n"
        "files and legacy files).\n"
        "[ ] Build completes successfully from source with "
        "clear instructions.\n"
        "\n"
        "More detailed checklist, please refer to:\n"
        "https://github.com/apache/cloudberry/wiki/Source-Release-Checklist\n"
        "\n"
        "Build/Install guides (for reference):\n"
        "- cloudberry: "
        "https://cloudberry.apache.org/docs/deployment/quick-build#for-apache-cloudberry-210\n"
        "- cloudberry-pxf:\n"
        "https://github.com/apache/cloudberry-pxf/blob/2.1.0-incubating-rc2/README.md\n"
        "- cloudberry-backup:\n"
        "https://github.com/apache/cloudberry-backup/blob/2.1.0-incubating-rc2/README.md\n"
        "\n"
        "To learn more about Apache Cloudberry (Incubating), "
        "please see\n"
        "https://cloudberry.apache.org/\n"
        "\n"
        "\n"
        "Best,\n"
        "Dianjin Wang\n"
        "On behalf of the Apache Cloudberry (Incubating) "
        "community\n"
        "\n"
        "---------------------------------------------------------------------\n"
        "To unsubscribe, e-mail: "
        "general-unsubscribe@incubator.apache.org\n"
        "For additional commands, e-mail: "
        "general-help@incubator.apache.org\n"
        "\n",
        "in-reply-to": "",
        "list": "general@incubator.apache.org",
    },
    "gqlc7syfwj4g1ltr18kozqb7l07g9rb5": {
        "mid": "gqlc7syfwj4g1ltr18kozqb7l07g9rb5",
        "tid": None,
        "epoch": 1774543585,
        "date": "2026/03/26 16:46:25",
        "subject": "Re: [VOTE] Release Apache Cloudberry (Incubating) 2.1.0-rc2",
        "message-id": "<CANwOBskREkXJq+VqCTskWy9_ekraJ=3ExsdMRUpz8OPz3r=uhg@mail.gmail.com>",
        "private": False,
        "from": "Shuxin Pan <ps...@apache.org>",
        "body": "+1(non-binding)\n"
        "\n"
        "Congratulations on the new release!\n"
        "\n"
        "Best,\n"
        "Shuxin Pan\n"
        "\n"
        "On Thu, Mar 26, 2026 at 12:39\u202fPM Dianjin Wang "
        "<wa...@gmail.com> wrote:\n"
        ">\n"
        "> Hello Incubator Community,\n"
        ">\n"
        "> This is a call for a vote to release Apache "
        "Cloudberry (Incubating) 2.1.0-rc2.\n"
        ">\n"
        "> The Apache Cloudberry (Incubating) community has "
        "voted to release\n"
        "> version 2.1.0-rc2. We now kindly request the "
        "Incubator PMC's approval.\n"
        ">\n"
        ">\n"
        "> **Key changes since 2.1.0-rc1**\n"
        ">\n"
        "> The main changes are to fix the license issues "
        "pointed out in the RC1,\n"
        "> including:\n"
        ">\n"
        "> - cloudberry:\n"
        "> * No changes. Fixes for the license typo and "
        "documentation updates\n"
        "> pointed out during the RC1 round will be included "
        "in the next release.\n"
        ">\n"
        "> - cloudberry-pxf\n"
        "> * Add `cloudberry-pxf-release.sh` to assist the "
        "release manager in\n"
        "> creating ASF releases.\n"
        "> * Update `Makefile` to include `fdw` in DEB/RPM "
        "packages.\n"
        "> * Remove `gradle-wrapper.jar` from the source "
        "tree; it is now\n"
        "> downloaded and validated during the build "
        "process.\n"
        "> * Add ASF license headers to files created by the "
        "Cloudberry community.\n"
        "> * Update the `LICENSE` file to reflect the latest "
        "changes from third-parties.\n"
        "> * Add a new `README.apache.md` to document "
        "historical attributions\n"
        "> and describe test archive files.\n"
        "> * Add a new `pom.xml` with necessary exclusions "
        "for running `mvn\n"
        "> apache-rat:check` during license audits.\n"
        "> * Add `.github/workflows/apache-rat-audit.yml` to "
        "perform regular\n"
        "> license checks on PRs and pushes.\n"
        ">\n"
        "> - cloudberry-backup\n"
        "> * Update the `LICENSE` file with correct "
        "open-source attributions.\n"
        "> * Add a new `README.apache.md` to document "
        "historical attributions\n"
        "> and describe test archive files.\n"
        "> * Add a new `pom.xml` with necessary exclusions "
        "for running `mvn\n"
        "> apache-rat:check` during license audits.\n"
        "> * Add `.github/workflows/apache-rat-audit.yml` to "
        "perform regular\n"
        "> license checks on PRs and pushes.\n"
        ">\n"
        ">\n"
        "> Community vote thread:\n"
        "> "
        "https://lists.apache.org/thread/7ozvb3808jxyyr105kbphhpj1dz5g7yk\n"
        ">\n"
        "> Vote result thread:\n"
        "> "
        "https://lists.apache.org/thread/xzqzp6scvxd00gfxx685nks7ykc7bpcr\n"
        ">\n"
        "> Release candidate artifacts:\n"
        "> "
        "https://dist.apache.org/repos/dist/dev/incubator/cloudberry/2.1.0-incubating-rc2/\n"
        ">\n"
        "> Git tag & commit for the release:\n"
        "> - "
        "https://github.com/apache/cloudberry/tree/2.1.0-incubating-rc2 "
        "(bdf90c5)\n"
        "> - "
        "https://github.com/apache/cloudberry-backup/tree/2.1.0-incubating-rc2\n"
        "> ( 3b5451f )\n"
        "> - "
        "https://github.com/apache/cloudberry-pxf/tree/2.1.0-incubating-rc2 "
        "(118f588)\n"
        ">\n"
        "> The artifacts have been signed with key\n"
        "> [9A36AA272348A207E193A49C500708B75754FB7C], "
        "corresponding to\n"
        "> djwang@apache.org, available here:\n"
        "> "
        "https://downloads.apache.org/incubator/cloudberry/KEYS\n"
        ">\n"
        "> Please vote on releasing this candidate as Apache "
        "Cloudberry (Incubating) 2.1.0.\n"
        ">\n"
        "> [ ] +1 Approve the release\n"
        "> [ ] 0 No opinion\n"
        "> [ ] -1 Disapprove (please explain why)\n"
        ">\n"
        "> This vote will be open for at least 72 hours.\n"
        ">\n"
        "> Checklist for reference:\n"
        ">\n"
        "> [ ] Download links are valid and accessible.\n"
        "> [ ] GPG signature is valid for the release "
        "artifact using the KEYS file.\n"
        "> [ ] SHA512 checksums are correct and verified.\n"
        "> [ ] Source release artifact filename includes "
        '"incubating".\n'
        "> [ ] LICENSE, NOTICE, and DISCLAIMER files exist "
        "and are accurate.\n"
        "> [ ] No unexpected binary files in the source "
        "release.\n"
        "> [ ] All source files have appropriate ASF headers "
        "(excluding generated\n"
        "> files and legacy files).\n"
        "> [ ] Build completes successfully from source with "
        "clear instructions.\n"
        ">\n"
        "> More detailed checklist, please refer to:\n"
        "> "
        "https://github.com/apache/cloudberry/wiki/Source-Release-Checklist\n"
        ">\n"
        "> Build/Install guides (for reference):\n"
        "> - cloudberry: "
        "https://cloudberry.apache.org/docs/deployment/quick-build#for-apache-cloudberry-210\n"
        "> - cloudberry-pxf:\n"
        "> "
        "https://github.com/apache/cloudberry-pxf/blob/2.1.0-incubating-rc2/README.md\n"
        "> - cloudberry-backup:\n"
        "> "
        "https://github.com/apache/cloudberry-backup/blob/2.1.0-incubating-rc2/README.md\n"
        ">\n"
        "> To learn more about Apache Cloudberry "
        "(Incubating), please see\n"
        "> https://cloudberry.apache.org/\n"
        ">\n"
        ">\n"
        "> Best,\n"
        "> Dianjin Wang\n"
        "> On behalf of the Apache Cloudberry (Incubating) "
        "community\n"
        ">\n"
        "> "
        "---------------------------------------------------------------------\n"
        "> To unsubscribe, e-mail: "
        "general-unsubscribe@incubator.apache.org\n"
        "> For additional commands, e-mail: "
        "general-help@incubator.apache.org\n"
        ">\n"
        "\n"
        "---------------------------------------------------------------------\n"
        "To unsubscribe, e-mail: "
        "general-unsubscribe@incubator.apache.org\n"
        "For additional commands, e-mail: "
        "general-help@incubator.apache.org\n"
        "\n",
        "in-reply-to": "<CACz0+mP279OmaTXiD44aMiw2u86e5JYaWg0j7d3SHWKPcaCgiQ@mail.gmail.com>",
        "list": "general@incubator.apache.org",
    },
    "s3r9zmkt90cjnx8921mvmojw2zdfgh8k": {
        "mid": "s3r9zmkt90cjnx8921mvmojw2zdfgh8k",
        "tid": None,
        "epoch": 1774678031,
        "date": "2026/03/28 06:07:11",
        "subject": "Re: [VOTE] Release Apache Cloudberry (Incubating) 2.1.0-rc2",
        "message-id": "<CAB8EV3RbE_JbJmhh4t8LaRqJJEA8r0TPvE3fTfkmZ5qetpH9_Q@mail.gmail.com>",
        "private": False,
        "from": "Jean-Baptiste Onofré <jb...@nanthrax.net>",
        "body": "+1 (binding)\n"
        "\n"
        "I checked:\n"
        "- source distribution\n"
        "-- incubating is in the name/version\n"
        "-- signature and checksum are good\n"
        "-- DISCLAIMER is present\n"
        '-- LICENSE is correct (nit: "see '
        'licenses/licenses/LICENSE-isc.txt" should\n'
        'be "see licenses/LICENSE-isc.txt")\n'
        "-- NOTICE is correct\n"
        "-- ASF header is present in expected files (as a "
        "bunch of code is coming\n"
        "from Greenplum so it's normal to preserve the "
        "header as stated in the\n"
        "LICENSE)\n"
        "-- No binary/compiled fille in the source "
        "distribution (.gz/.bz2 files are\n"
        "test data, it's ok, though the ASF release policy "
        "does prefer avoiding\n"
        "binary content where possible)\n"
        "- backup binary distribution\n"
        "-- incubating is in the name/version\n"
        "-- signature and checksum are good\n"
        "-- DISCLAIMER is present\n"
        "-- LICENSE and NOTICE are good (nit: I would "
        "suggest to include\n"
        "https://github.com/greenplum-db/gpbackup-archive/blob/main/NOTICE "
        "in the\n"
        "NOTICE if you think it's helpful)\n"
        "-- pxf binary distribution\n"
        "-- incubating is in the name/version\n"
        "-- signature and checksum are good\n"
        "-- DISCLAIMER is present\n"
        "-- LICENSE and NOTICE are good (just a comment for "
        "other reviewers: the\n"
        "LICENSE file mentions derivation from Greenplum PXF "
        "(VMware), but the\n"
        "NOTICE file mentions Apache HAWQ instead. Both are "
        "historically accurate\n"
        "(HAWQ begat Greenplum PXF begat Cloudberry PXF), so "
        "this is fine — the\n"
        "NOTICE covers the ASF-side lineage while LICENSE "
        "covers the VMware-side\n"
        "lineage. Nothing needs to be changed.\n"
        "\n"
        "Thanks,\n"
        "Regards\n"
        "JB\n"
        "\n"
        "On Thu, Mar 26, 2026 at 5:39\u202fAM Dianjin Wang "
        "<wa...@gmail.com> wrote:\n"
        "\n"
        "> Hello Incubator Community,\n"
        ">\n"
        "> This is a call for a vote to release Apache "
        "Cloudberry (Incubating)\n"
        "> 2.1.0-rc2.\n"
        ">\n"
        "> The Apache Cloudberry (Incubating) community has "
        "voted to release\n"
        "> version 2.1.0-rc2. We now kindly request the "
        "Incubator PMC's approval.\n"
        ">\n"
        ">\n"
        "> **Key changes since 2.1.0-rc1**\n"
        ">\n"
        "> The main changes are to fix the license issues "
        "pointed out in the RC1,\n"
        "> including:\n"
        ">\n"
        "> - cloudberry:\n"
        "> * No changes. Fixes for the license typo and "
        "documentation updates\n"
        "> pointed out during the RC1 round will be included "
        "in the next release.\n"
        ">\n"
        "> - cloudberry-pxf\n"
        "> * Add `cloudberry-pxf-release.sh` to assist the "
        "release manager in\n"
        "> creating ASF releases.\n"
        "> * Update `Makefile` to include `fdw` in DEB/RPM "
        "packages.\n"
        "> * Remove `gradle-wrapper.jar` from the source "
        "tree; it is now\n"
        "> downloaded and validated during the build "
        "process.\n"
        "> * Add ASF license headers to files created by the "
        "Cloudberry community.\n"
        "> * Update the `LICENSE` file to reflect the latest "
        "changes from\n"
        "> third-parties.\n"
        "> * Add a new `README.apache.md` to document "
        "historical attributions\n"
        "> and describe test archive files.\n"
        "> * Add a new `pom.xml` with necessary exclusions "
        "for running `mvn\n"
        "> apache-rat:check` during license audits.\n"
        "> * Add `.github/workflows/apache-rat-audit.yml` to "
        "perform regular\n"
        "> license checks on PRs and pushes.\n"
        ">\n"
        "> - cloudberry-backup\n"
        "> * Update the `LICENSE` file with correct "
        "open-source attributions.\n"
        "> * Add a new `README.apache.md` to document "
        "historical attributions\n"
        "> and describe test archive files.\n"
        "> * Add a new `pom.xml` with necessary exclusions "
        "for running `mvn\n"
        "> apache-rat:check` during license audits.\n"
        "> * Add `.github/workflows/apache-rat-audit.yml` to "
        "perform regular\n"
        "> license checks on PRs and pushes.\n"
        ">\n"
        ">\n"
        "> Community vote thread:\n"
        "> "
        "https://lists.apache.org/thread/7ozvb3808jxyyr105kbphhpj1dz5g7yk\n"
        ">\n"
        "> Vote result thread:\n"
        "> "
        "https://lists.apache.org/thread/xzqzp6scvxd00gfxx685nks7ykc7bpcr\n"
        ">\n"
        "> Release candidate artifacts:\n"
        ">\n"
        "> "
        "https://dist.apache.org/repos/dist/dev/incubator/cloudberry/2.1.0-incubating-rc2/\n"
        ">\n"
        "> Git tag & commit for the release:\n"
        "> - "
        "https://github.com/apache/cloudberry/tree/2.1.0-incubating-rc2 "
        "(bdf90c5)\n"
        "> - "
        "https://github.com/apache/cloudberry-backup/tree/2.1.0-incubating-rc2\n"
        "> ( 3b5451f )\n"
        "> - "
        "https://github.com/apache/cloudberry-pxf/tree/2.1.0-incubating-rc2\n"
        "> (118f588)\n"
        ">\n"
        "> The artifacts have been signed with key\n"
        "> [9A36AA272348A207E193A49C500708B75754FB7C], "
        "corresponding to\n"
        "> djwang@apache.org, available here:\n"
        "> "
        "https://downloads.apache.org/incubator/cloudberry/KEYS\n"
        ">\n"
        "> Please vote on releasing this candidate as Apache "
        "Cloudberry (Incubating)\n"
        "> 2.1.0.\n"
        ">\n"
        "> [ ] +1 Approve the release\n"
        "> [ ] 0 No opinion\n"
        "> [ ] -1 Disapprove (please explain why)\n"
        ">\n"
        "> This vote will be open for at least 72 hours.\n"
        ">\n"
        "> Checklist for reference:\n"
        ">\n"
        "> [ ] Download links are valid and accessible.\n"
        "> [ ] GPG signature is valid for the release "
        "artifact using the KEYS file.\n"
        "> [ ] SHA512 checksums are correct and verified.\n"
        "> [ ] Source release artifact filename includes "
        '"incubating".\n'
        "> [ ] LICENSE, NOTICE, and DISCLAIMER files exist "
        "and are accurate.\n"
        "> [ ] No unexpected binary files in the source "
        "release.\n"
        "> [ ] All source files have appropriate ASF headers "
        "(excluding generated\n"
        "> files and legacy files).\n"
        "> [ ] Build completes successfully from source with "
        "clear instructions.\n"
        ">\n"
        "> More detailed checklist, please refer to:\n"
        "> "
        "https://github.com/apache/cloudberry/wiki/Source-Release-Checklist\n"
        ">\n"
        "> Build/Install guides (for reference):\n"
        "> - cloudberry:\n"
        "> "
        "https://cloudberry.apache.org/docs/deployment/quick-build#for-apache-cloudberry-210\n"
        "> - cloudberry-pxf:\n"
        ">\n"
        "> "
        "https://github.com/apache/cloudberry-pxf/blob/2.1.0-incubating-rc2/README.md\n"
        "> - cloudberry-backup:\n"
        ">\n"
        "> "
        "https://github.com/apache/cloudberry-backup/blob/2.1.0-incubating-rc2/README.md\n"
        ">\n"
        "> To learn more about Apache Cloudberry "
        "(Incubating), please see\n"
        "> https://cloudberry.apache.org/\n"
        ">\n"
        ">\n"
        "> Best,\n"
        "> Dianjin Wang\n"
        "> On behalf of the Apache Cloudberry (Incubating) "
        "community\n"
        ">\n"
        "> "
        "---------------------------------------------------------------------\n"
        "> To unsubscribe, e-mail: "
        "general-unsubscribe@incubator.apache.org\n"
        "> For additional commands, e-mail: "
        "general-help@incubator.apache.org\n"
        ">\n"
        ">\n",
        "in-reply-to": "<CACz0+mP279OmaTXiD44aMiw2u86e5JYaWg0j7d3SHWKPcaCgiQ@mail.gmail.com>",
        "list": "general@incubator.apache.org",
    },
    "4oqn1ldo215c2917flfzo0xj2sovmw3h": {
        "mid": "4oqn1ldo215c2917flfzo0xj2sovmw3h",
        "tid": None,
        "epoch": 1775629469,
        "date": "2026/04/08 06:24:29",
        "subject": "Re: [VOTE] Release Apache Cloudberry (Incubating) 2.1.0-rc2",
        "message-id": "<CACz0+mNbqzZ9TOgCxKFNskhR1Z0zuK_CVbhqFjc25WqqrYji2A@mail.gmail.com>",
        "private": False,
        "from": "Dianjin Wang <wa...@gmail.com>",
        "body": "+1 (non-binding, Apache Cloudberry PPMC)\n"
        "\n"
        "\n"
        "Best,\n"
        "Dianjin Wang\n"
        "\n"
        "On Thu, Mar 26, 2026 at 12:39\u202fPM Dianjin Wang "
        "<wa...@gmail.com> wrote:\n"
        ">\n"
        "> Hello Incubator Community,\n"
        ">\n"
        "> This is a call for a vote to release Apache "
        "Cloudberry (Incubating) 2.1.0-rc2.\n"
        ">\n"
        "> The Apache Cloudberry (Incubating) community has "
        "voted to release\n"
        "> version 2.1.0-rc2. We now kindly request the "
        "Incubator PMC's approval.\n"
        ">\n"
        ">\n"
        "> **Key changes since 2.1.0-rc1**\n"
        ">\n"
        "> The main changes are to fix the license issues "
        "pointed out in the RC1,\n"
        "> including:\n"
        ">\n"
        "> - cloudberry:\n"
        "> * No changes. Fixes for the license typo and "
        "documentation updates\n"
        "> pointed out during the RC1 round will be included "
        "in the next release.\n"
        ">\n"
        "> - cloudberry-pxf\n"
        "> * Add `cloudberry-pxf-release.sh` to assist the "
        "release manager in\n"
        "> creating ASF releases.\n"
        "> * Update `Makefile` to include `fdw` in DEB/RPM "
        "packages.\n"
        "> * Remove `gradle-wrapper.jar` from the source "
        "tree; it is now\n"
        "> downloaded and validated during the build "
        "process.\n"
        "> * Add ASF license headers to files created by the "
        "Cloudberry community.\n"
        "> * Update the `LICENSE` file to reflect the latest "
        "changes from third-parties.\n"
        "> * Add a new `README.apache.md` to document "
        "historical attributions\n"
        "> and describe test archive files.\n"
        "> * Add a new `pom.xml` with necessary exclusions "
        "for running `mvn\n"
        "> apache-rat:check` during license audits.\n"
        "> * Add `.github/workflows/apache-rat-audit.yml` to "
        "perform regular\n"
        "> license checks on PRs and pushes.\n"
        ">\n"
        "> - cloudberry-backup\n"
        "> * Update the `LICENSE` file with correct "
        "open-source attributions.\n"
        "> * Add a new `README.apache.md` to document "
        "historical attributions\n"
        "> and describe test archive files.\n"
        "> * Add a new `pom.xml` with necessary exclusions "
        "for running `mvn\n"
        "> apache-rat:check` during license audits.\n"
        "> * Add `.github/workflows/apache-rat-audit.yml` to "
        "perform regular\n"
        "> license checks on PRs and pushes.\n"
        ">\n"
        ">\n"
        "> Community vote thread:\n"
        "> "
        "https://lists.apache.org/thread/7ozvb3808jxyyr105kbphhpj1dz5g7yk\n"
        ">\n"
        "> Vote result thread:\n"
        "> "
        "https://lists.apache.org/thread/xzqzp6scvxd00gfxx685nks7ykc7bpcr\n"
        ">\n"
        "> Release candidate artifacts:\n"
        "> "
        "https://dist.apache.org/repos/dist/dev/incubator/cloudberry/2.1.0-incubating-rc2/\n"
        ">\n"
        "> Git tag & commit for the release:\n"
        "> - "
        "https://github.com/apache/cloudberry/tree/2.1.0-incubating-rc2 "
        "(bdf90c5)\n"
        "> - "
        "https://github.com/apache/cloudberry-backup/tree/2.1.0-incubating-rc2\n"
        "> ( 3b5451f )\n"
        "> - "
        "https://github.com/apache/cloudberry-pxf/tree/2.1.0-incubating-rc2 "
        "(118f588)\n"
        ">\n"
        "> The artifacts have been signed with key\n"
        "> [9A36AA272348A207E193A49C500708B75754FB7C], "
        "corresponding to\n"
        "> djwang@apache.org, available here:\n"
        "> "
        "https://downloads.apache.org/incubator/cloudberry/KEYS\n"
        ">\n"
        "> Please vote on releasing this candidate as Apache "
        "Cloudberry (Incubating) 2.1.0.\n"
        ">\n"
        "> [ ] +1 Approve the release\n"
        "> [ ] 0 No opinion\n"
        "> [ ] -1 Disapprove (please explain why)\n"
        ">\n"
        "> This vote will be open for at least 72 hours.\n"
        ">\n"
        "> Checklist for reference:\n"
        ">\n"
        "> [ ] Download links are valid and accessible.\n"
        "> [ ] GPG signature is valid for the release "
        "artifact using the KEYS file.\n"
        "> [ ] SHA512 checksums are correct and verified.\n"
        "> [ ] Source release artifact filename includes "
        '"incubating".\n'
        "> [ ] LICENSE, NOTICE, and DISCLAIMER files exist "
        "and are accurate.\n"
        "> [ ] No unexpected binary files in the source "
        "release.\n"
        "> [ ] All source files have appropriate ASF headers "
        "(excluding generated\n"
        "> files and legacy files).\n"
        "> [ ] Build completes successfully from source with "
        "clear instructions.\n"
        ">\n"
        "> More detailed checklist, please refer to:\n"
        "> "
        "https://github.com/apache/cloudberry/wiki/Source-Release-Checklist\n"
        ">\n"
        "> Build/Install guides (for reference):\n"
        "> - cloudberry: "
        "https://cloudberry.apache.org/docs/deployment/quick-build#for-apache-cloudberry-210\n"
        "> - cloudberry-pxf:\n"
        "> "
        "https://github.com/apache/cloudberry-pxf/blob/2.1.0-incubating-rc2/README.md\n"
        "> - cloudberry-backup:\n"
        "> "
        "https://github.com/apache/cloudberry-backup/blob/2.1.0-incubating-rc2/README.md\n"
        ">\n"
        "> To learn more about Apache Cloudberry "
        "(Incubating), please see\n"
        "> https://cloudberry.apache.org/\n"
        ">\n"
        ">\n"
        "> Best,\n"
        "> Dianjin Wang\n"
        "> On behalf of the Apache Cloudberry (Incubating) "
        "community\n"
        "\n"
        "---------------------------------------------------------------------\n"
        "To unsubscribe, e-mail: "
        "general-unsubscribe@incubator.apache.org\n"
        "For additional commands, e-mail: "
        "general-help@incubator.apache.org\n"
        "\n",
        "in-reply-to": "<CACz0+mP279OmaTXiD44aMiw2u86e5JYaWg0j7d3SHWKPcaCgiQ@mail.gmail.com>",
        "list": "general@incubator.apache.org",
    },
    "tkdhqs8bk706fccjzpn5h2hdz2vy3fy5": {
        "mid": "tkdhqs8bk706fccjzpn5h2hdz2vy3fy5",
        "tid": None,
        "epoch": 1775643840,
        "date": "2026/04/08 10:24:00",
        "subject": "Re: [VOTE] Release Apache Cloudberry (Incubating) 2.1.0-rc2",
        "message-id": "<CANwOBskJMAdXRL5veChjUH53EVp=LV=wc_5MCe9JF2ow11bW6A@mail.gmail.com>",
        "private": False,
        "from": "Shuxin Pan <ps...@apache.org>",
        "body": "+1 (non-binding)\n"
        "\n"
        "I verified:\n"
        "- artifact links\n"
        "- signatures and SHA512 checksums\n"
        "- incubating naming\n"
        "- release tags/commits\n"
        "- LICENSE/NOTICE/DISCLAIMER presence\n"
        "- RAT checks with 0 unknown licenses\n"
        "\n"
        "I did not perform full build validation.\n"
        "\n"
        "Best,\n"
        "Shuxin Pan\n"
        "\n"
        "On Thu, Mar 26, 2026 at 12:39\u202fPM Dianjin Wang "
        "<wa...@gmail.com> wrote:\n"
        ">\n"
        "> Hello Incubator Community,\n"
        ">\n"
        "> This is a call for a vote to release Apache "
        "Cloudberry (Incubating) 2.1.0-rc2.\n"
        ">\n"
        "> The Apache Cloudberry (Incubating) community has "
        "voted to release\n"
        "> version 2.1.0-rc2. We now kindly request the "
        "Incubator PMC's approval.\n"
        ">\n"
        ">\n"
        "> **Key changes since 2.1.0-rc1**\n"
        ">\n"
        "> The main changes are to fix the license issues "
        "pointed out in the RC1,\n"
        "> including:\n"
        ">\n"
        "> - cloudberry:\n"
        "> * No changes. Fixes for the license typo and "
        "documentation updates\n"
        "> pointed out during the RC1 round will be included "
        "in the next release.\n"
        ">\n"
        "> - cloudberry-pxf\n"
        "> * Add `cloudberry-pxf-release.sh` to assist the "
        "release manager in\n"
        "> creating ASF releases.\n"
        "> * Update `Makefile` to include `fdw` in DEB/RPM "
        "packages.\n"
        "> * Remove `gradle-wrapper.jar` from the source "
        "tree; it is now\n"
        "> downloaded and validated during the build "
        "process.\n"
        "> * Add ASF license headers to files created by the "
        "Cloudberry community.\n"
        "> * Update the `LICENSE` file to reflect the latest "
        "changes from third-parties.\n"
        "> * Add a new `README.apache.md` to document "
        "historical attributions\n"
        "> and describe test archive files.\n"
        "> * Add a new `pom.xml` with necessary exclusions "
        "for running `mvn\n"
        "> apache-rat:check` during license audits.\n"
        "> * Add `.github/workflows/apache-rat-audit.yml` to "
        "perform regular\n"
        "> license checks on PRs and pushes.\n"
        ">\n"
        "> - cloudberry-backup\n"
        "> * Update the `LICENSE` file with correct "
        "open-source attributions.\n"
        "> * Add a new `README.apache.md` to document "
        "historical attributions\n"
        "> and describe test archive files.\n"
        "> * Add a new `pom.xml` with necessary exclusions "
        "for running `mvn\n"
        "> apache-rat:check` during license audits.\n"
        "> * Add `.github/workflows/apache-rat-audit.yml` to "
        "perform regular\n"
        "> license checks on PRs and pushes.\n"
        ">\n"
        ">\n"
        "> Community vote thread:\n"
        "> "
        "https://lists.apache.org/thread/7ozvb3808jxyyr105kbphhpj1dz5g7yk\n"
        ">\n"
        "> Vote result thread:\n"
        "> "
        "https://lists.apache.org/thread/xzqzp6scvxd00gfxx685nks7ykc7bpcr\n"
        ">\n"
        "> Release candidate artifacts:\n"
        "> "
        "https://dist.apache.org/repos/dist/dev/incubator/cloudberry/2.1.0-incubating-rc2/\n"
        ">\n"
        "> Git tag & commit for the release:\n"
        "> - "
        "https://github.com/apache/cloudberry/tree/2.1.0-incubating-rc2 "
        "(bdf90c5)\n"
        "> - "
        "https://github.com/apache/cloudberry-backup/tree/2.1.0-incubating-rc2\n"
        "> ( 3b5451f )\n"
        "> - "
        "https://github.com/apache/cloudberry-pxf/tree/2.1.0-incubating-rc2 "
        "(118f588)\n"
        ">\n"
        "> The artifacts have been signed with key\n"
        "> [9A36AA272348A207E193A49C500708B75754FB7C], "
        "corresponding to\n"
        "> djwang@apache.org, available here:\n"
        "> "
        "https://downloads.apache.org/incubator/cloudberry/KEYS\n"
        ">\n"
        "> Please vote on releasing this candidate as Apache "
        "Cloudberry (Incubating) 2.1.0.\n"
        ">\n"
        "> [ ] +1 Approve the release\n"
        "> [ ] 0 No opinion\n"
        "> [ ] -1 Disapprove (please explain why)\n"
        ">\n"
        "> This vote will be open for at least 72 hours.\n"
        ">\n"
        "> Checklist for reference:\n"
        ">\n"
        "> [ ] Download links are valid and accessible.\n"
        "> [ ] GPG signature is valid for the release "
        "artifact using the KEYS file.\n"
        "> [ ] SHA512 checksums are correct and verified.\n"
        "> [ ] Source release artifact filename includes "
        '"incubating".\n'
        "> [ ] LICENSE, NOTICE, and DISCLAIMER files exist "
        "and are accurate.\n"
        "> [ ] No unexpected binary files in the source "
        "release.\n"
        "> [ ] All source files have appropriate ASF headers "
        "(excluding generated\n"
        "> files and legacy files).\n"
        "> [ ] Build completes successfully from source with "
        "clear instructions.\n"
        ">\n"
        "> More detailed checklist, please refer to:\n"
        "> "
        "https://github.com/apache/cloudberry/wiki/Source-Release-Checklist\n"
        ">\n"
        "> Build/Install guides (for reference):\n"
        "> - cloudberry: "
        "https://cloudberry.apache.org/docs/deployment/quick-build#for-apache-cloudberry-210\n"
        "> - cloudberry-pxf:\n"
        "> "
        "https://github.com/apache/cloudberry-pxf/blob/2.1.0-incubating-rc2/README.md\n"
        "> - cloudberry-backup:\n"
        "> "
        "https://github.com/apache/cloudberry-backup/blob/2.1.0-incubating-rc2/README.md\n"
        ">\n"
        "> To learn more about Apache Cloudberry "
        "(Incubating), please see\n"
        "> https://cloudberry.apache.org/\n"
        ">\n"
        ">\n"
        "> Best,\n"
        "> Dianjin Wang\n"
        "> On behalf of the Apache Cloudberry (Incubating) "
        "community\n"
        ">\n"
        "> "
        "---------------------------------------------------------------------\n"
        "> To unsubscribe, e-mail: "
        "general-unsubscribe@incubator.apache.org\n"
        "> For additional commands, e-mail: "
        "general-help@incubator.apache.org\n"
        ">\n"
        "\n"
        "---------------------------------------------------------------------\n"
        "To unsubscribe, e-mail: "
        "general-unsubscribe@incubator.apache.org\n"
        "For additional commands, e-mail: "
        "general-help@incubator.apache.org\n"
        "\n",
        "in-reply-to": "<CACz0+mP279OmaTXiD44aMiw2u86e5JYaWg0j7d3SHWKPcaCgiQ@mail.gmail.com>",
        "list": "general@incubator.apache.org",
    },
    "rq6p8zn0w23wd02dkgvh7qmq5tpydowd": {
        "mid": "rq6p8zn0w23wd02dkgvh7qmq5tpydowd",
        "tid": None,
        "epoch": 1775697942,
        "date": "2026/04/09 01:25:42",
        "subject": "Re: [VOTE] Release Apache Cloudberry (Incubating) 2.1.0-rc2",
        "message-id": "<CA+QaCW+jvn6Pd91b+6iDXE7UWA1QW=QH8QT1bOueLHt+pz=hJA@mail.gmail.com>",
        "private": False,
        "from": "Willem Jiang <wi...@gmail.com>",
        "body": "+1 binding （ningjiang）\n"
        "Here is what I checked.\n"
        "[x] Download links are valid.\n"
        "[x] Checksums and signatures.\n"
        "[x] LICENSE/NOTICE files exist\n"
        "[x] DISCLAIMER files exist\n"
        "[x] Artifacts have the Incubating in the name\n"
        "[x] No unexpected binary files\n"
        "\n"
        "Willem Jiang\n"
        "\n"
        "\n"
        "On Thu, Mar 26, 2026 at 12:39\u202fPM Dianjin Wang "
        "<wa...@gmail.com> wrote:\n"
        ">\n"
        "> Hello Incubator Community,\n"
        ">\n"
        "> This is a call for a vote to release Apache "
        "Cloudberry (Incubating) 2.1.0-rc2.\n"
        ">\n"
        "> The Apache Cloudberry (Incubating) community has "
        "voted to release\n"
        "> version 2.1.0-rc2. We now kindly request the "
        "Incubator PMC's approval.\n"
        ">\n"
        ">\n"
        "> **Key changes since 2.1.0-rc1**\n"
        ">\n"
        "> The main changes are to fix the license issues "
        "pointed out in the RC1,\n"
        "> including:\n"
        ">\n"
        "> - cloudberry:\n"
        "> * No changes. Fixes for the license typo and "
        "documentation updates\n"
        "> pointed out during the RC1 round will be included "
        "in the next release.\n"
        ">\n"
        "> - cloudberry-pxf\n"
        "> * Add `cloudberry-pxf-release.sh` to assist the "
        "release manager in\n"
        "> creating ASF releases.\n"
        "> * Update `Makefile` to include `fdw` in DEB/RPM "
        "packages.\n"
        "> * Remove `gradle-wrapper.jar` from the source "
        "tree; it is now\n"
        "> downloaded and validated during the build "
        "process.\n"
        "> * Add ASF license headers to files created by the "
        "Cloudberry community.\n"
        "> * Update the `LICENSE` file to reflect the latest "
        "changes from third-parties.\n"
        "> * Add a new `README.apache.md` to document "
        "historical attributions\n"
        "> and describe test archive files.\n"
        "> * Add a new `pom.xml` with necessary exclusions "
        "for running `mvn\n"
        "> apache-rat:check` during license audits.\n"
        "> * Add `.github/workflows/apache-rat-audit.yml` to "
        "perform regular\n"
        "> license checks on PRs and pushes.\n"
        ">\n"
        "> - cloudberry-backup\n"
        "> * Update the `LICENSE` file with correct "
        "open-source attributions.\n"
        "> * Add a new `README.apache.md` to document "
        "historical attributions\n"
        "> and describe test archive files.\n"
        "> * Add a new `pom.xml` with necessary exclusions "
        "for running `mvn\n"
        "> apache-rat:check` during license audits.\n"
        "> * Add `.github/workflows/apache-rat-audit.yml` to "
        "perform regular\n"
        "> license checks on PRs and pushes.\n"
        ">\n"
        ">\n"
        "> Community vote thread:\n"
        "> "
        "https://lists.apache.org/thread/7ozvb3808jxyyr105kbphhpj1dz5g7yk\n"
        ">\n"
        "> Vote result thread:\n"
        "> "
        "https://lists.apache.org/thread/xzqzp6scvxd00gfxx685nks7ykc7bpcr\n"
        ">\n"
        "> Release candidate artifacts:\n"
        "> "
        "https://dist.apache.org/repos/dist/dev/incubator/cloudberry/2.1.0-incubating-rc2/\n"
        ">\n"
        "> Git tag & commit for the release:\n"
        "> - "
        "https://github.com/apache/cloudberry/tree/2.1.0-incubating-rc2 "
        "(bdf90c5)\n"
        "> - "
        "https://github.com/apache/cloudberry-backup/tree/2.1.0-incubating-rc2\n"
        "> ( 3b5451f )\n"
        "> - "
        "https://github.com/apache/cloudberry-pxf/tree/2.1.0-incubating-rc2 "
        "(118f588)\n"
        ">\n"
        "> The artifacts have been signed with key\n"
        "> [9A36AA272348A207E193A49C500708B75754FB7C], "
        "corresponding to\n"
        "> djwang@apache.org, available here:\n"
        "> "
        "https://downloads.apache.org/incubator/cloudberry/KEYS\n"
        ">\n"
        "> Please vote on releasing this candidate as Apache "
        "Cloudberry (Incubating) 2.1.0.\n"
        ">\n"
        "> [ ] +1 Approve the release\n"
        "> [ ] 0 No opinion\n"
        "> [ ] -1 Disapprove (please explain why)\n"
        ">\n"
        "> This vote will be open for at least 72 hours.\n"
        ">\n"
        "> Checklist for reference:\n"
        ">\n"
        "> [ ] Download links are valid and accessible.\n"
        "> [ ] GPG signature is valid for the release "
        "artifact using the KEYS file.\n"
        "> [ ] SHA512 checksums are correct and verified.\n"
        "> [ ] Source release artifact filename includes "
        '"incubating".\n'
        "> [ ] LICENSE, NOTICE, and DISCLAIMER files exist "
        "and are accurate.\n"
        "> [ ] No unexpected binary files in the source "
        "release.\n"
        "> [ ] All source files have appropriate ASF headers "
        "(excluding generated\n"
        "> files and legacy files).\n"
        "> [ ] Build completes successfully from source with "
        "clear instructions.\n"
        ">\n"
        "> More detailed checklist, please refer to:\n"
        "> "
        "https://github.com/apache/cloudberry/wiki/Source-Release-Checklist\n"
        ">\n"
        "> Build/Install guides (for reference):\n"
        "> - cloudberry: "
        "https://cloudberry.apache.org/docs/deployment/quick-build#for-apache-cloudberry-210\n"
        "> - cloudberry-pxf:\n"
        "> "
        "https://github.com/apache/cloudberry-pxf/blob/2.1.0-incubating-rc2/README.md\n"
        "> - cloudberry-backup:\n"
        "> "
        "https://github.com/apache/cloudberry-backup/blob/2.1.0-incubating-rc2/README.md\n"
        ">\n"
        "> To learn more about Apache Cloudberry "
        "(Incubating), please see\n"
        "> https://cloudberry.apache.org/\n"
        ">\n"
        ">\n"
        "> Best,\n"
        "> Dianjin Wang\n"
        "> On behalf of the Apache Cloudberry (Incubating) "
        "community\n"
        ">\n"
        "> "
        "---------------------------------------------------------------------\n"
        "> To unsubscribe, e-mail: "
        "general-unsubscribe@incubator.apache.org\n"
        "> For additional commands, e-mail: "
        "general-help@incubator.apache.org\n"
        ">\n"
        "\n"
        "---------------------------------------------------------------------\n"
        "To unsubscribe, e-mail: "
        "general-unsubscribe@incubator.apache.org\n"
        "For additional commands, e-mail: "
        "general-help@incubator.apache.org\n"
        "\n",
        "in-reply-to": "<CACz0+mP279OmaTXiD44aMiw2u86e5JYaWg0j7d3SHWKPcaCgiQ@mail.gmail.com>",
        "list": "general@incubator.apache.org",
    },
    "msxgc1kydbwpscojv5pq7p8dr91l7blr": {
        "mid": "msxgc1kydbwpscojv5pq7p8dr91l7blr",
        "tid": None,
        "epoch": 1775735784,
        "date": "2026/04/09 11:56:24",
        "subject": "Re: [VOTE] Release Apache Cloudberry (Incubating) 2.1.0-rc2",
        "message-id": "<CA+9ODHHR4Arm=4ZYo=5k2x33zMib+fjmmoZ2kTBxyyVf6RJgdg@mail.gmail.com>",
        "private": False,
        "from": "Alin Jerpelea <je...@gmail.com>",
        "body": "+1 binding\n"
        "\n"
        "I checked.\n"
        "Download links\n"
        "LICENSE/NOTICE files\n"
        "DISCLAIMER file\n"
        "Incubating name\n"
        "\n"
        "\n"
        "On Thu, Apr 9, 2026 at 3:27\u202fAM Willem Jiang "
        "<wi...@gmail.com> wrote:\n"
        "\n"
        "> +1 binding （ningjiang）\n"
        "> Here is what I checked.\n"
        "> [x] Download links are valid.\n"
        "> [x] Checksums and signatures.\n"
        "> [x] LICENSE/NOTICE files exist\n"
        "> [x] DISCLAIMER files exist\n"
        "> [x] Artifacts have the Incubating in the name\n"
        "> [x] No unexpected binary files\n"
        ">\n"
        "> Willem Jiang\n"
        ">\n"
        ">\n"
        "> On Thu, Mar 26, 2026 at 12:39\u202fPM Dianjin "
        "Wang <wa...@gmail.com>\n"
        "> wrote:\n"
        "> >\n"
        "> > Hello Incubator Community,\n"
        "> >\n"
        "> > This is a call for a vote to release Apache "
        "Cloudberry (Incubating)\n"
        "> 2.1.0-rc2.\n"
        "> >\n"
        "> > The Apache Cloudberry (Incubating) community "
        "has voted to release\n"
        "> > version 2.1.0-rc2. We now kindly request the "
        "Incubator PMC's approval.\n"
        "> >\n"
        "> >\n"
        "> > **Key changes since 2.1.0-rc1**\n"
        "> >\n"
        "> > The main changes are to fix the license issues "
        "pointed out in the RC1,\n"
        "> > including:\n"
        "> >\n"
        "> > - cloudberry:\n"
        "> > * No changes. Fixes for the license typo and "
        "documentation updates\n"
        "> > pointed out during the RC1 round will be "
        "included in the next release.\n"
        "> >\n"
        "> > - cloudberry-pxf\n"
        "> > * Add `cloudberry-pxf-release.sh` to assist the "
        "release manager in\n"
        "> > creating ASF releases.\n"
        "> > * Update `Makefile` to include `fdw` in DEB/RPM "
        "packages.\n"
        "> > * Remove `gradle-wrapper.jar` from the source "
        "tree; it is now\n"
        "> > downloaded and validated during the build "
        "process.\n"
        "> > * Add ASF license headers to files created by "
        "the Cloudberry community.\n"
        "> > * Update the `LICENSE` file to reflect the "
        "latest changes from\n"
        "> third-parties.\n"
        "> > * Add a new `README.apache.md` to document "
        "historical attributions\n"
        "> > and describe test archive files.\n"
        "> > * Add a new `pom.xml` with necessary exclusions "
        "for running `mvn\n"
        "> > apache-rat:check` during license audits.\n"
        "> > * Add `.github/workflows/apache-rat-audit.yml` "
        "to perform regular\n"
        "> > license checks on PRs and pushes.\n"
        "> >\n"
        "> > - cloudberry-backup\n"
        "> > * Update the `LICENSE` file with correct "
        "open-source attributions.\n"
        "> > * Add a new `README.apache.md` to document "
        "historical attributions\n"
        "> > and describe test archive files.\n"
        "> > * Add a new `pom.xml` with necessary exclusions "
        "for running `mvn\n"
        "> > apache-rat:check` during license audits.\n"
        "> > * Add `.github/workflows/apache-rat-audit.yml` "
        "to perform regular\n"
        "> > license checks on PRs and pushes.\n"
        "> >\n"
        "> >\n"
        "> > Community vote thread:\n"
        "> > "
        "https://lists.apache.org/thread/7ozvb3808jxyyr105kbphhpj1dz5g7yk\n"
        "> >\n"
        "> > Vote result thread:\n"
        "> > "
        "https://lists.apache.org/thread/xzqzp6scvxd00gfxx685nks7ykc7bpcr\n"
        "> >\n"
        "> > Release candidate artifacts:\n"
        "> >\n"
        "> "
        "https://dist.apache.org/repos/dist/dev/incubator/cloudberry/2.1.0-incubating-rc2/\n"
        "> >\n"
        "> > Git tag & commit for the release:\n"
        "> > - "
        "https://github.com/apache/cloudberry/tree/2.1.0-incubating-rc2\n"
        "> (bdf90c5)\n"
        "> > - "
        "https://github.com/apache/cloudberry-backup/tree/2.1.0-incubating-rc2\n"
        "> > ( 3b5451f )\n"
        "> > - "
        "https://github.com/apache/cloudberry-pxf/tree/2.1.0-incubating-rc2\n"
        "> (118f588)\n"
        "> >\n"
        "> > The artifacts have been signed with key\n"
        "> > [9A36AA272348A207E193A49C500708B75754FB7C], "
        "corresponding to\n"
        "> > djwang@apache.org, available here:\n"
        "> > "
        "https://downloads.apache.org/incubator/cloudberry/KEYS\n"
        "> >\n"
        "> > Please vote on releasing this candidate as "
        "Apache Cloudberry\n"
        "> (Incubating) 2.1.0.\n"
        "> >\n"
        "> > [ ] +1 Approve the release\n"
        "> > [ ] 0 No opinion\n"
        "> > [ ] -1 Disapprove (please explain why)\n"
        "> >\n"
        "> > This vote will be open for at least 72 hours.\n"
        "> >\n"
        "> > Checklist for reference:\n"
        "> >\n"
        "> > [ ] Download links are valid and accessible.\n"
        "> > [ ] GPG signature is valid for the release "
        "artifact using the KEYS file.\n"
        "> > [ ] SHA512 checksums are correct and verified.\n"
        "> > [ ] Source release artifact filename includes "
        '"incubating".\n'
        "> > [ ] LICENSE, NOTICE, and DISCLAIMER files exist "
        "and are accurate.\n"
        "> > [ ] No unexpected binary files in the source "
        "release.\n"
        "> > [ ] All source files have appropriate ASF "
        "headers (excluding generated\n"
        "> > files and legacy files).\n"
        "> > [ ] Build completes successfully from source "
        "with clear instructions.\n"
        "> >\n"
        "> > More detailed checklist, please refer to:\n"
        "> > "
        "https://github.com/apache/cloudberry/wiki/Source-Release-Checklist\n"
        "> >\n"
        "> > Build/Install guides (for reference):\n"
        "> > - cloudberry:\n"
        "> "
        "https://cloudberry.apache.org/docs/deployment/quick-build#for-apache-cloudberry-210\n"
        "> > - cloudberry-pxf:\n"
        "> >\n"
        "> "
        "https://github.com/apache/cloudberry-pxf/blob/2.1.0-incubating-rc2/README.md\n"
        "> > - cloudberry-backup:\n"
        "> >\n"
        "> "
        "https://github.com/apache/cloudberry-backup/blob/2.1.0-incubating-rc2/README.md\n"
        "> >\n"
        "> > To learn more about Apache Cloudberry "
        "(Incubating), please see\n"
        "> > https://cloudberry.apache.org/\n"
        "> >\n"
        "> >\n"
        "> > Best,\n"
        "> > Dianjin Wang\n"
        "> > On behalf of the Apache Cloudberry (Incubating) "
        "community\n"
        "> >\n"
        "> > "
        "---------------------------------------------------------------------\n"
        "> > To unsubscribe, e-mail: "
        "general-unsubscribe@incubator.apache.org\n"
        "> > For additional commands, e-mail: "
        "general-help@incubator.apache.org\n"
        "> >\n"
        ">\n"
        "> "
        "---------------------------------------------------------------------\n"
        "> To unsubscribe, e-mail: "
        "general-unsubscribe@incubator.apache.org\n"
        "> For additional commands, e-mail: "
        "general-help@incubator.apache.org\n"
        ">\n"
        ">\n",
        "in-reply-to": "<CA+QaCW+jvn6Pd91b+6iDXE7UWA1QW=QH8QT1bOueLHt+pz=hJA@mail.gmail.com>",
        "list": "general@incubator.apache.org",
    },
    "j9yoh66yx9j1ccdgqpys7blhoyqzshh7": {
        "mid": "j9yoh66yx9j1ccdgqpys7blhoyqzshh7",
        "tid": None,
        "epoch": 1775792280,
        "date": "2026/04/10 03:38:00",
        "subject": "[RESULT] [VOTE] Release Apache Cloudberry (Incubating) 2.1.0-rc2",
        "message-id": "<CACz0+mPJDvH9xgwdKzNz2y523DnJasKqwh0LLg_XC9XZvkFa9w@mail.gmail.com>",
        "private": False,
        "from": "Dianjin Wang <wa...@gmail.com>",
        "body": "Hello Incubator Community,\n"
        "\n"
        "The vote to release Apache Cloudberry (Incubating) "
        "2.1.0-rc2 has\n"
        "passed with 3 +1 binding votes, 2 +1 non-binding, "
        "no +0 or -1 votes.\n"
        "\n"
        "+1 binding:\n"
        "- Jean-Baptiste Onofré (binding)\n"
        "- Willem Jiang (binding)\n"
        "- Alin Jerpelea (binding)\n"
        "\n"
        "+1 Non-binding:\n"
        "- Shuxin Pan (non-binding)\n"
        "- Dianjin Wang (non-binding)\n"
        "\n"
        "Vote thread:\n"
        "https://lists.apache.org/thread/ojromk12r5y8802jp3qy16w9hq0fxk1o\n"
        "\n"
        "Thanks for reviewing and voting for our release "
        "candidate.\n"
        "\n"
        "We will proceed with publishing the approved "
        "artifacts and sending out the\n"
        "announcement soon.\n"
        "\n"
        "\n"
        "Best,\n"
        "Dianjin Wang\n"
        "\n"
        "---------------------------------------------------------------------\n"
        "To unsubscribe, e-mail: "
        "general-unsubscribe@incubator.apache.org\n"
        "For additional commands, e-mail: "
        "general-help@incubator.apache.org\n"
        "\n",
        "in-reply-to": "",
        "list": "general@incubator.apache.org",
    },
}

CLOUDBERRY_STATS: dict[str, Any] = {
    "took": 42,
    "firstYear": 2026,
    "lastYear": 2026,
    "hits": 15,
    "domain": "incubator.apache.org",
    "name": "general",
    "list": "general@incubator.apache.org",
    "emails": {
        "pxcqfrbl8bdp256yxtxx5zr60y79nrkn": {
            "id": "pxcqfrbl8bdp256yxtxx5zr60y79nrkn",
            "tid": None,
            "epoch": 1773293940,
            "subject": "[VOTE] Release Apache Cloudberry (Incubating) 2.1.0-rc1",
            "message-id": "<CACz0+mOZtQY0MH-1Kkt4y966YP8nqMmyyRfhC1kDLqAxpoTeyg@mail.gmail.com>",
            "private": False,
            "from": "Dianjin Wang <wa...@gmail.com>",
            "attachments": 0,
        },
        "xfcf4rxpmj071no5jcx9693mh1mmyml9": {
            "id": "xfcf4rxpmj071no5jcx9693mh1mmyml9",
            "tid": None,
            "epoch": 1773384550,
            "subject": "Re: [VOTE] Release Apache Cloudberry (Incubating) 2.1.0-rc1",
            "message-id": "<CAB8EV3RpJWVGfnQEGXxTYdVrWJtBOrtktQMp6xcqhf8nX6U7Mg@mail.gmail.com>",
            "private": False,
            "from": "Jean-Baptiste Onofré <jb...@nanthrax.net>",
            "attachments": 0,
        },
        "dzzl7thfszl78m7cgxpc9h91pk5s0rmd": {
            "id": "dzzl7thfszl78m7cgxpc9h91pk5s0rmd",
            "tid": None,
            "epoch": 1773388262,
            "subject": "Re: [VOTE] Release Apache Cloudberry (Incubating) 2.1.0-rc1",
            "message-id": "<CAB8EV3T_AAMTLmMhDhcprutJ2MQgVMHzAzkzrYqELGnhin76fw@mail.gmail.com>",
            "private": False,
            "from": "Jean-Baptiste Onofré <jb...@nanthrax.net>",
            "attachments": 0,
        },
        "l72ymslr2mtk4bjj0gjsysf47ph8nnsn": {
            "id": "l72ymslr2mtk4bjj0gjsysf47ph8nnsn",
            "tid": None,
            "epoch": 1773401117,
            "subject": "Re: [VOTE] Release Apache Cloudberry (Incubating) 2.1.0-rc1",
            "message-id": "<pony-907a914e-dee6-41e9-a74a-03f991b02b60-general@incubator.apache.org>",
            "private": False,
            "from": "Dianjin Wang <dj...@apache.org>",
            "attachments": 0,
        },
        "zd2jtq0cso6rotj1hosnx155cttypb1d": {
            "id": "zd2jtq0cso6rotj1hosnx155cttypb1d",
            "tid": None,
            "epoch": 1773403152,
            "subject": "Re: [VOTE] Release Apache Cloudberry (Incubating) 2.1.0-rc1",
            "message-id": "<CAB8EV3QJT91_2QhZwW_6tdszoankqBpo_DFKUZz4Z45sNBd9_Q@mail.gmail.com>",
            "private": False,
            "from": "Jean-Baptiste Onofré <jb...@nanthrax.net>",
            "attachments": 0,
        },
        "hrj8wfcyjllygq93qjzgbzmcyfg9h4f4": {
            "id": "hrj8wfcyjllygq93qjzgbzmcyfg9h4f4",
            "tid": None,
            "epoch": 1773455030,
            "subject": "Re: [VOTE] Release Apache Cloudberry (Incubating) 2.1.0-rc1",
            "message-id": "<3C645584-B05F-44BB-85F6-6E8F9B1E8171@classsoftware.com>",
            "private": False,
            "from": "Justin Mclean <ju...@classsoftware.com>",
            "attachments": 0,
        },
        "xdg2b89wkhrljql5lm2j0wlzccld505o": {
            "id": "xdg2b89wkhrljql5lm2j0wlzccld505o",
            "tid": None,
            "epoch": 1773628257,
            "subject": "Re: [VOTE] Release Apache Cloudberry (Incubating) 2.1.0-rc1",
            "message-id": "<pony-ac969478-8e1a-43a6-aa48-ae576683fa5f-general@incubator.apache.org>",
            "private": False,
            "from": "Dianjin Wang <dj...@apache.org>",
            "attachments": 0,
        },
        "ojromk12r5y8802jp3qy16w9hq0fxk1o": {
            "id": "ojromk12r5y8802jp3qy16w9hq0fxk1o",
            "tid": None,
            "epoch": 1774499940,
            "subject": "[VOTE] Release Apache Cloudberry (Incubating) 2.1.0-rc2",
            "message-id": "<CACz0+mP279OmaTXiD44aMiw2u86e5JYaWg0j7d3SHWKPcaCgiQ@mail.gmail.com>",
            "private": False,
            "from": "Dianjin Wang <wa...@gmail.com>",
            "attachments": 0,
        },
        "gqlc7syfwj4g1ltr18kozqb7l07g9rb5": {
            "id": "gqlc7syfwj4g1ltr18kozqb7l07g9rb5",
            "tid": None,
            "epoch": 1774543585,
            "subject": "Re: [VOTE] Release Apache Cloudberry (Incubating) 2.1.0-rc2",
            "message-id": "<CANwOBskREkXJq+VqCTskWy9_ekraJ=3ExsdMRUpz8OPz3r=uhg@mail.gmail.com>",
            "private": False,
            "from": "Shuxin Pan <ps...@apache.org>",
            "attachments": 0,
        },
        "s3r9zmkt90cjnx8921mvmojw2zdfgh8k": {
            "id": "s3r9zmkt90cjnx8921mvmojw2zdfgh8k",
            "tid": None,
            "epoch": 1774678031,
            "subject": "Re: [VOTE] Release Apache Cloudberry (Incubating) 2.1.0-rc2",
            "message-id": "<CAB8EV3RbE_JbJmhh4t8LaRqJJEA8r0TPvE3fTfkmZ5qetpH9_Q@mail.gmail.com>",
            "private": False,
            "from": "Jean-Baptiste Onofré <jb...@nanthrax.net>",
            "attachments": 0,
        },
        "4oqn1ldo215c2917flfzo0xj2sovmw3h": {
            "id": "4oqn1ldo215c2917flfzo0xj2sovmw3h",
            "tid": None,
            "epoch": 1775629469,
            "subject": "Re: [VOTE] Release Apache Cloudberry (Incubating) 2.1.0-rc2",
            "message-id": "<CACz0+mNbqzZ9TOgCxKFNskhR1Z0zuK_CVbhqFjc25WqqrYji2A@mail.gmail.com>",
            "private": False,
            "from": "Dianjin Wang <wa...@gmail.com>",
            "attachments": 0,
        },
        "tkdhqs8bk706fccjzpn5h2hdz2vy3fy5": {
            "id": "tkdhqs8bk706fccjzpn5h2hdz2vy3fy5",
            "tid": None,
            "epoch": 1775643840,
            "subject": "Re: [VOTE] Release Apache Cloudberry (Incubating) 2.1.0-rc2",
            "message-id": "<CANwOBskJMAdXRL5veChjUH53EVp=LV=wc_5MCe9JF2ow11bW6A@mail.gmail.com>",
            "private": False,
            "from": "Shuxin Pan <ps...@apache.org>",
            "attachments": 0,
        },
        "rq6p8zn0w23wd02dkgvh7qmq5tpydowd": {
            "id": "rq6p8zn0w23wd02dkgvh7qmq5tpydowd",
            "tid": None,
            "epoch": 1775697942,
            "subject": "Re: [VOTE] Release Apache Cloudberry (Incubating) 2.1.0-rc2",
            "message-id": "<CA+QaCW+jvn6Pd91b+6iDXE7UWA1QW=QH8QT1bOueLHt+pz=hJA@mail.gmail.com>",
            "private": False,
            "from": "Willem Jiang <wi...@gmail.com>",
            "attachments": 0,
        },
        "msxgc1kydbwpscojv5pq7p8dr91l7blr": {
            "id": "msxgc1kydbwpscojv5pq7p8dr91l7blr",
            "tid": None,
            "epoch": 1775735784,
            "subject": "Re: [VOTE] Release Apache Cloudberry (Incubating) 2.1.0-rc2",
            "message-id": "<CA+9ODHHR4Arm=4ZYo=5k2x33zMib+fjmmoZ2kTBxyyVf6RJgdg@mail.gmail.com>",
            "private": False,
            "from": "Alin Jerpelea <je...@gmail.com>",
            "attachments": 0,
        },
        "j9yoh66yx9j1ccdgqpys7blhoyqzshh7": {
            "id": "j9yoh66yx9j1ccdgqpys7blhoyqzshh7",
            "tid": None,
            "epoch": 1775792280,
            "subject": "[RESULT] [VOTE] Release Apache Cloudberry (Incubating) 2.1.0-rc2",
            "message-id": "<CACz0+mPJDvH9xgwdKzNz2y523DnJasKqwh0LLg_XC9XZvkFa9w@mail.gmail.com>",
            "private": False,
            "from": "Dianjin Wang <wa...@gmail.com>",
            "attachments": 0,
        },
    },
}
